# Generated by Django 6.0.3 on 2026-03-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
